---

- name: load mysql database
  mysql_db: name=wordpress state=import target=/vagrant/data/mithpressgamma.sql.bz2

- name: Copy WordPress config file
  template: src=wp-config.php.j2 dest=/var/www/wordpress/wp-config.php


