# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "mith.yml"
    ansible.extra_vars = {
      ansible_ssh_user: "vagrant"
    }
    ansible.groups = {
      "wp-server" => ["default"]
    }
  end
end
