---
- name: install mysql
  apt: name={{ item }} state=present
  with_items:
   - mysql-server
   # python-mysqldb is for Ansible.
   - python-mysqldb

- name: Update root password
  mysql_user: name=root password="{{ mysql_root_password }}"