# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.33.15"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = ENV["PLAYBOOK"] or "wp.yml"
    ansible.playbook = "mithpress.yml"
    ansible.inventory_path = "hosts"
    ansible.limit = "wordpress"
    ansible.extra_vars = {
      ansible_ssh_user: "vagrant"
    }
    #ansible.groups = {
    #  "wp-server" => ["default"]
    #}
  end
end
